# Generated by Django 4.1.1 on 2022-10-27 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_historicalorder_superintendente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalorder',
            name='sol_autorizada_por',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sol_autorizada_por',
        ),
    ]
