# Generated by Django 4.1.1 on 2022-10-14 04:31

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='monto_inicial_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('MXN', 'Peso mexicano'), ('USD', 'US Dollar')], default='MXN', editable=False, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='saldo_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('MXN', 'Peso mexicano'), ('USD', 'US Dollar')], default='MXN', editable=False, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='tipo_de_cambio_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('MXN', 'Peso mexicano'), ('USD', 'US Dollar')], default='MXN', editable=False, max_length=3, null=True),
        ),
    ]
