# Generated by Django 4.1.1 on 2022-10-14 04:31

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subproyecto',
            name='presupuesto_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('MXN', 'Peso mexicano'), ('USD', 'US Dollar')], default='MXN', editable=False, max_length=3, null=True),
        ),
    ]
