# Generated by Django 4.1.1 on 2022-11-16 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_perfil',
            name='almacen',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='tipo_perfil',
            name='autorizacion',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='tipo_perfil',
            name='compras',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='tipo_perfil',
            name='configuracion',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='tipo_perfil',
            name='historicos',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='tipo_perfil',
            name='reportes',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='tipo_perfil',
            name='requisiciones',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='tipo_perfil',
            name='solicitudes',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='tipo_perfil',
            name='tesoreria',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
