# Generated by Django 4.1.1 on 2022-11-16 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_tipo_perfil_autorizar_req_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_perfil',
            name='superintendente',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='tipo_perfil',
            name='supervisor',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
