# Generated by Django 4.1.1 on 2022-11-16 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_tipo_perfil_almacenista'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_perfil',
            name='comprador',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
