# Generated by Django 4.1.1 on 2022-11-16 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_tipo_perfil_comprador'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_perfil',
            name='oc_gerencia',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='tipo_perfil',
            name='oc_superintendencia',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
