# Generated by Django 4.1.1 on 2022-10-14 04:31

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulocomprado',
            name='precio_unitario_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('MXN', 'Peso mexicano'), ('USD', 'US Dollar')], default='MXN', editable=False, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='costo_fletes_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('MXN', 'Peso mexicano'), ('USD', 'US Dollar')], default='MXN', editable=False, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='costo_iva_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('MXN', 'Peso mexicano'), ('USD', 'US Dollar')], default='MXN', editable=False, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='costo_oc_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('MXN', 'Peso mexicano'), ('USD', 'US Dollar')], default='MXN', editable=False, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='impuestos_adicionales_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('MXN', 'Peso mexicano'), ('USD', 'US Dollar')], default='MXN', editable=False, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='monto_anticipo_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('MXN', 'Peso mexicano'), ('USD', 'US Dollar')], default='MXN', editable=False, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='tipo_de_cambio_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('MXN', 'Peso mexicano'), ('USD', 'US Dollar')], default='MXN', editable=False, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='historicalarticulocomprado',
            name='precio_unitario_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('MXN', 'Peso mexicano'), ('USD', 'US Dollar')], default='MXN', editable=False, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompra',
            name='costo_fletes_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('MXN', 'Peso mexicano'), ('USD', 'US Dollar')], default='MXN', editable=False, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompra',
            name='costo_iva_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('MXN', 'Peso mexicano'), ('USD', 'US Dollar')], default='MXN', editable=False, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompra',
            name='costo_oc_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('MXN', 'Peso mexicano'), ('USD', 'US Dollar')], default='MXN', editable=False, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompra',
            name='impuestos_adicionales_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('MXN', 'Peso mexicano'), ('USD', 'US Dollar')], default='MXN', editable=False, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompra',
            name='monto_anticipo_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('MXN', 'Peso mexicano'), ('USD', 'US Dollar')], default='MXN', editable=False, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompra',
            name='tipo_de_cambio_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('MXN', 'Peso mexicano'), ('USD', 'US Dollar')], default='MXN', editable=False, max_length=3, null=True),
        ),
    ]
